spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auctionapp
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    mode: HTML

mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true