spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auctionapp
    username: auctionapp
    password: auctionapp
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    mode: HTML

server:
  servlet:
    context-path: /auctionapp

mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true